# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49fce900c7f148c3fa4ea34669fc161f6f2c8e379a18f16cd0e2311f1287bec4938af06fe286597b8579543e08adaf9495fc3b35387ca5a26a9bc5858ee569a8

test:
  secret_key_base: e6bc1dee2b71a55f79eaca10a0e06e0453054abe1d91a95dd68f0a0241f56606eb8f37fa830e33e90ea64eb0196dc8de715cc43685ec44410acd7b1b3be91df9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
